kind: pipeline
type: docker
name: Cypres

trigger:
  event:
    - push

steps:
  - name: app-build
    image: ghcr.io/cirruslabs/flutter:3.19.2
    commands:
      - cd ./Sources/
      - flutter build apk

  #- name: build-web
  #  image: ghcr.io/cirruslabs/flutter:3.19.2
  #  commands:
  #    - cd ./Sources/
  #    - flutter build web --web-renderer canvaskit

  - name: code-analysis
    image: ghcr.io/cirruslabs/flutter:3.19.2
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    commands:
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - sonar-scanner -D sonar.projectKey=Cypres -D sonar.sources=./Sources/ -D sonar.host.url=https://codefirst.iut.uca.fr/sonar
    depends_on: [app-build] 